import type { ResearchResult } from './types';

export interface DiscordSendParams {
  botToken: string;
  channelId: string;
  applicantName: string;
  applicantEmail: string;
  result: ResearchResult;
  pdfBuffer: Buffer;
}

/**
 * Sends the applicant details, research summary, and PDF attachment to a
 * Discord channel using the bot REST API's multipart/form-data upload.
 */
export async function sendToDiscord(params: DiscordSendParams): Promise<void> {
  const { botToken, channelId, applicantName, applicantEmail, result, pdfBuffer } = params;

  if (!botToken || !channelId) {
    throw new Error('Discord bot token and channel ID are required.');
  }

  const embed = {
    title: `Company Research Report: ${result.companyName}`,
    color: 0x4f6ef7,
    fields: [
      { name: 'Applicant Name', value: applicantName || 'N/A', inline: true },
      { name: 'Applicant Email', value: applicantEmail || 'N/A', inline: true },
      { name: 'Company Name', value: result.companyName || 'N/A', inline: false },
      { name: 'Company Website', value: result.website || 'N/A', inline: false }
    ],
    timestamp: new Date().toISOString()
  };

  const payload = {
    content: `New company research report generated by ${applicantName || 'an applicant'}.`,
    embeds: [embed]
  };

  const fileName = `${(result.companyName || 'company').replace(/[^a-z0-9]+/gi, '_')}_report.pdf`;

  const form = new FormData();
  form.append('payload_json', JSON.stringify(payload));
  form.append(
    'files[0]',
    new Blob([pdfBuffer], { type: 'application/pdf' }),
    fileName
  );

  const res = await fetch(`https://discord.com/api/v10/channels/${channelId}/messages`, {
    method: 'POST',
    headers: {
      Authorization: `Bot ${botToken}`
    },
    body: form,
    signal: AbortSignal.timeout(20000)
  });

  if (res.status === 401) {
    throw new Error('Discord rejected the bot token.');
  }
  if (res.status === 403) {
    throw new Error('Discord bot lacks permission to post in that channel.');
  }
  if (res.status === 404) {
    throw new Error('Discord channel ID not found.');
  }
  if (!res.ok) {
    const body = await res.text().catch(() => '');
    throw new Error(`Discord API request failed with status ${res.status}. ${body.slice(0, 200)}`);
  }
}
